<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ctl00MainContenttxtLoanAmount</name>
   <tag></tag>
   <elementGuidId>2e502507-b6cd-43b0-b9c5-73fe3fa162d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_txtLoanAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_txtLoanAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d5e66b0-5801-4d81-ba4d-15c364300689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$txtLoanAmount</value>
      <webElementGuid>815afaf0-6d96-489e-9d51-db085fe83271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>119c9777-ee0b-49da-a1fe-922fc24758de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>ee9e729a-c738-4381-b16d-4786940f6d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_txtLoanAmount</value>
      <webElementGuid>20247eb3-0493-4fc3-8d16-8952d22de22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputtextbox</value>
      <webElementGuid>242cbc9c-5d36-4e2c-9362-de52ddb63d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_txtLoanAmount&quot;)</value>
      <webElementGuid>f66fb5c8-2240-4900-9197-ada42d4e17f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_txtLoanAmount']</value>
      <webElementGuid>de37368e-85ce-4999-88ca-ff73850ccaec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[3]/article/div[4]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>14adfd1a-bb46-4670-82b9-dfcdf9c1ec53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>df465b70-b204-4153-a332-4c437ae788a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$MainContent$txtLoanAmount' and @type = 'text' and @id = 'ctl00_MainContent_txtLoanAmount']</value>
      <webElementGuid>727270a7-fe6f-472f-9476-9c927019a464</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
