<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Harshal</name>
   <tag></tag>
   <elementGuidId>43291735-72e0-45e3-ad39-e78da124951b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_lblUserFullName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_MainContent_lblUserFullName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6fbb8c92-fd55-4283-bda2-55595c37117d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_lblUserFullName</value>
      <webElementGuid>d5c42c3c-1fd5-4a11-b98f-cc8d671d4df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Harshal</value>
      <webElementGuid>db5e3977-539b-430f-b29f-80be8bfeb914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_lblUserFullName&quot;)</value>
      <webElementGuid>0d695be0-f1ee-4778-9e38-5b08fd867650</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_MainContent_lblUserFullName']</value>
      <webElementGuid>d7f1cc65-a1d7-4750-a491-9b8fc0f798ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[3]/article/h2/span</value>
      <webElementGuid>29b9bb06-585e-4d76-b1de-e4fcf54c9754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lender Management'])[1]/following::span[1]</value>
      <webElementGuid>96e42b07-40d2-4533-8473-e3ecef3f5144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'ctl00_MainContent_lblUserFullName', '&quot;', ')')])[1]/preceding::span[1]</value>
      <webElementGuid>bd68a9c2-80d3-4cef-9fa4-1ce15183c580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Harshal']/parent::*</value>
      <webElementGuid>285f1187-256e-4033-923c-52aaa13c8679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>cbf40d62-d437-4d0d-90d4-5b47f9907f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_MainContent_lblUserFullName' and (text() = 'Harshal' or . = 'Harshal')]</value>
      <webElementGuid>7de51ae0-80c1-4a81-a6e4-c1a94bfd5f48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
