<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_150</name>
   <tag></tag>
   <elementGuidId>fe8b1dac-2ad7-4929-b785-1e11e5261bb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_lblMonthlyPayment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_MainContent_lblMonthlyPayment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7510030c-a2a7-4590-9df8-53a4538b35d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_lblMonthlyPayment</value>
      <webElementGuid>2bdf9198-4a2c-4b71-a663-4cd11e818c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formValue</value>
      <webElementGuid>2d6385d9-b332-4c37-8168-0f83fe95a41b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$ 150</value>
      <webElementGuid>1f71c706-9e16-4535-b1b3-62f68c27c260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_lblMonthlyPayment&quot;)</value>
      <webElementGuid>a475e3ee-a342-440a-9cc1-0971b6601ae8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_MainContent_lblMonthlyPayment']</value>
      <webElementGuid>9ee68fa4-e5da-4833-9f01-3539732df95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[3]/article/div[4]/table/tbody/tr[2]/td[2]/span</value>
      <webElementGuid>265e23a7-2d7f-474e-82bf-2910c9cdbfc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimum Monthly Payment:'])[1]/following::span[1]</value>
      <webElementGuid>c46496fc-fb0a-445d-96ed-f68a2b37f319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan amount must be numeric.'])[1]/following::span[1]</value>
      <webElementGuid>cd395164-6b33-4d40-ad3c-83465583bc9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculate'])[1]/preceding::span[1]</value>
      <webElementGuid>f0d36309-fdcf-4619-a206-8f5390845c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'ctl00_MainContent_lblMonthlyPayment', '&quot;', ')')])[1]/preceding::span[1]</value>
      <webElementGuid>e710cf2c-551d-4107-bb45-e98aad50a41f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$ 150']/parent::*</value>
      <webElementGuid>f1b2fe83-b0c4-4328-aede-6890ed760e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/span</value>
      <webElementGuid>d4a1f932-c1aa-4568-baf8-649a9bea9087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_MainContent_lblMonthlyPayment' and (text() = '$ 150' or . = '$ 150')]</value>
      <webElementGuid>0854251d-a5a6-4bae-95f5-91d6d96a3dc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
