<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User Name_ctl00MainContenttxtUserName</name>
   <tag></tag>
   <elementGuidId>6e6765be-4496-4443-ae5b-e678cca0a644</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_txtUserName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_txtUserName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68b8bfad-703b-4bdb-8817-a5f2d1e7f74e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$txtUserName</value>
      <webElementGuid>a1d47673-ff96-4a6b-8f3b-07db123201a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>946c3c23-bb3b-452b-8e4d-2c1a9ba6abb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_txtUserName</value>
      <webElementGuid>48d58a20-5eb9-4df0-890c-cf26bfc0ad73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginInput</value>
      <webElementGuid>bfe9934f-6ca7-4dad-a8ff-f0d5e3bb3c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_txtUserName&quot;)</value>
      <webElementGuid>0148cc4b-3976-46ed-ba88-0721ca8b9cd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_txtUserName']</value>
      <webElementGuid>045ec182-8b9f-42cf-a0c5-113f773bd97b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[3]/article/div/input</value>
      <webElementGuid>e516859b-c50d-4460-a965-b413a232af06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/input</value>
      <webElementGuid>96757b19-8d1e-4040-a304-5f4d231d8a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$MainContent$txtUserName' and @type = 'text' and @id = 'ctl00_MainContent_txtUserName']</value>
      <webElementGuid>6a2f97f1-2e9a-44a6-9f3b-7589f7fe8695</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
