<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User Name_ctl00MainContenttxtUserName</name>
   <tag></tag>
   <elementGuidId>05efaf69-76fd-4269-842c-483c29858349</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_txtUserName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_txtUserName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c6fdbb6-909f-423b-b2ed-37ddffb81daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$txtUserName</value>
      <webElementGuid>82b5c574-38d7-453a-9398-0b073a623da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b9027c8d-9b80-4291-b700-b88121634724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_txtUserName</value>
      <webElementGuid>7656b0e3-e48e-4692-82c8-b5afc83ceaa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginInput</value>
      <webElementGuid>b853eb4d-648f-43a9-ba9d-fb2b67894155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_txtUserName&quot;)</value>
      <webElementGuid>1599f957-6a75-4057-9951-1b92b0861de1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_txtUserName']</value>
      <webElementGuid>779a3a39-d339-4e1c-bba9-a9e15465213d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[3]/article/div/input</value>
      <webElementGuid>7c4f06b3-c9b6-430b-9df2-8501a068212b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/input</value>
      <webElementGuid>01bd43f7-3464-40f6-8830-8f8ffe34cb65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$MainContent$txtUserName' and @type = 'text' and @id = 'ctl00_MainContent_txtUserName']</value>
      <webElementGuid>bb3fd35a-c629-4d1e-9658-ee09c8661b09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
