<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Calculator_dealerhome</name>
   <tag></tag>
   <elementGuidId>9e893568-93ad-49b3-9310-10b55e34e91a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_DealerNav_lnkCalculator</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_MainContent_DealerNav_lnkCalculator']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7cc52510-d124-4ac6-9834-bf60efc7ac71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_DealerNav_lnkCalculator</value>
      <webElementGuid>b714d661-8216-4507-8ded-8d745d3105df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4ff8c127-f9aa-4134-b6b5-5e4d1a2fadeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$MainContent$DealerNav$lnkCalculator','')</value>
      <webElementGuid>43d23040-b6e5-4385-9e29-f9cc942b4dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Calculator</value>
      <webElementGuid>9c9c5549-b5de-4eaa-a654-d5fcef559819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_DealerNav_lnkCalculator&quot;)</value>
      <webElementGuid>63e3e5ca-c3e6-4c3c-b27a-adac2a0555ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_MainContent_DealerNav_lnkCalculator']</value>
      <webElementGuid>2ce55bd1-cf2e-4489-9ed1-73e6eae47d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[3]/article/div[3]/a</value>
      <webElementGuid>c52fd23a-d911-4923-b6fb-618c9f6223d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Calculator')]</value>
      <webElementGuid>4bcd81f4-7f90-4b25-867f-0d5659db800a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::a[1]</value>
      <webElementGuid>be9940c9-b27a-4f16-a235-48c6c1b71498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dealer Home Page'])[1]/following::a[2]</value>
      <webElementGuid>b1eabdfd-0fd0-4a98-bec3-b71300846132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print Blank App'])[1]/preceding::a[1]</value>
      <webElementGuid>4a1cf53a-213e-41ed-b0bd-eaa36d47a039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter App Data'])[1]/preceding::a[2]</value>
      <webElementGuid>56be1057-b4bc-4f63-8b11-cd61ae28c5ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Calculator']/parent::*</value>
      <webElementGuid>9fb0bdcb-0bb0-47b4-83dd-ccb730ec4f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$MainContent$DealerNav$lnkCalculator','')&quot;)]</value>
      <webElementGuid>bc07168f-0e9c-47d4-8d1b-16188efe065d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>5a934e7a-78f5-4f42-841a-2322049e41b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_MainContent_DealerNav_lnkCalculator' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$MainContent$DealerNav$lnkCalculator&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Calculator' or . = 'Calculator')]</value>
      <webElementGuid>5526ab1a-b2e2-4f44-8018-1e09f0362e2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
