<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Germain</name>
   <tag></tag>
   <elementGuidId>8055225b-40e4-42b4-b5a0-5ccf0c6adc55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_MainContent_DealerSearchResult1_grdResults_ctl02_lnkShopName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_DealerSearchResult1_grdResults_ctl02_lnkShopName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cb7f6614-f965-4a36-a24a-07eaeb22f444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_DealerSearchResult1_grdResults_ctl02_lnkShopName</value>
      <webElementGuid>c312101c-1b69-4da3-9621-004158fd8856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$MainContent$DealerSearchResult1$grdResults$ctl02$lnkShopName&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>4dfb9082-47a3-4b33-86a6-ef300dd60d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Germain</value>
      <webElementGuid>b5acb5e1-bcdb-4aa4-9417-c50215d16fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_DealerSearchResult1_grdResults_ctl02_lnkShopName&quot;)</value>
      <webElementGuid>d7973b71-79e1-4a2f-af19-6bb3a89a61e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_MainContent_DealerSearchResult1_grdResults_ctl02_lnkShopName']</value>
      <webElementGuid>e790bfdb-7033-48c1-b6f9-96cccc00d2e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_MainContent_DealerSearchResult1_grdResults']/tbody/tr[4]/td[2]/a</value>
      <webElementGuid>71ca2657-3131-4d18-9333-0117ceee513e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Germain')]</value>
      <webElementGuid>21cc4457-ec04-43fc-b1a4-1607cc602689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/following::a[1]</value>
      <webElementGuid>07b0bbae-f98f-477f-88db-2901618c2f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/following::a[2]</value>
      <webElementGuid>cb447693-1f8b-44dd-b7f8-c892f8cdc5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mechanical'])[1]/preceding::a[1]</value>
      <webElementGuid>a173be6a-8e4b-4d4c-8e36-b7934544f2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes'])[1]/preceding::a[1]</value>
      <webElementGuid>3d3e7a6d-1e91-4273-8ad0-e7d27381c64e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Germain']/parent::*</value>
      <webElementGuid>d9c0c6cd-f25a-4d52-bbbb-49a783e76d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$MainContent$DealerSearchResult1$grdResults$ctl02$lnkShopName&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>73bee8bd-3d57-4486-a099-cc2929dfb675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/a</value>
      <webElementGuid>3de7efb8-29eb-46f5-b956-891ee970e87c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_MainContent_DealerSearchResult1_grdResults_ctl02_lnkShopName' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$MainContent$DealerSearchResult1$grdResults$ctl02$lnkShopName&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))' and (text() = 'Germain' or . = 'Germain')]</value>
      <webElementGuid>805693e9-51de-43a7-bc7e-8c774579af91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
