<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Show Prospects_ctl00MainContentchkAll</name>
   <tag></tag>
   <elementGuidId>5fc9f101-9640-4488-a14b-a86e9a74df73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_chkAll']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_chkAll</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a8cbf0f-1554-40dd-914d-a131c8ca82fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_chkAll</value>
      <webElementGuid>29bfd684-3181-4ed6-a25f-3a738114fe90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f05c3f62-bfdf-4df4-bbe8-ebc6a300cf2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$chkAll</value>
      <webElementGuid>7df32ff8-f915-497f-bfd2-7ef27cfed2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_chkAll&quot;)</value>
      <webElementGuid>cc845af6-fafb-461e-bb5e-314e971c9a6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_chkAll']</value>
      <webElementGuid>48d24be8-ef49-4b38-93b1-a47a22ddd462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='t2']/tbody/tr[4]/td/input</value>
      <webElementGuid>2728216f-1a2d-4b47-bb22-c03d8ceb1a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/input</value>
      <webElementGuid>94c1e887-ef39-4ad3-9485-c70d19074700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_MainContent_chkAll' and @type = 'checkbox' and @name = 'ctl00$MainContent$chkAll']</value>
      <webElementGuid>d1e350e2-dbfc-436f-a868-856a6e63fb05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
