<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Calculate</name>
   <tag></tag>
   <elementGuidId>4c89fc02-af7c-4ac0-a51e-e66a39376ee1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_MainContent_lnkCalculate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_lnkCalculate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4b513291-c559-453e-8c29-997acb63eda2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_lnkCalculate</value>
      <webElementGuid>f32da77e-3517-4dea-8536-ece13e43c68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>49cbc311-a15a-41f3-9d9b-ce8e067ff86c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$MainContent$lnkCalculate&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>9dbaaf46-bc50-4d7b-95b4-f51287ff1cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Calculate</value>
      <webElementGuid>a506fb4a-90a4-44a4-8ef0-3af10633ff75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_lnkCalculate&quot;)</value>
      <webElementGuid>84e01fd7-7cc3-46e3-bc32-d4368daf6457</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_MainContent_lnkCalculate']</value>
      <webElementGuid>4dc0b597-580d-442e-98ef-c87598050342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[3]/article/div[4]/table/tbody/tr[4]/td[2]/a</value>
      <webElementGuid>e0a2d017-55e7-47d5-8b0a-0cbb734d5d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Calculate')]</value>
      <webElementGuid>abbf7eb4-cb11-4b31-b8a7-2c704d1fa461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimum Monthly Payment:'])[1]/following::a[1]</value>
      <webElementGuid>411bf1a7-2ef8-4e86-9b6d-bb853a3ad9de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan amount must be numeric.'])[1]/following::a[1]</value>
      <webElementGuid>936b3079-518a-4b6e-a501-728a0e0abe0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'ctl00_MainContent_lnkCalculate', '&quot;', ')')])[1]/preceding::a[1]</value>
      <webElementGuid>b81f1b26-6924-4875-8231-c3a4191a81a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Calculate']/parent::*</value>
      <webElementGuid>47a8d322-d645-4833-8365-2cd157cbb3a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$MainContent$lnkCalculate&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>33510f7d-d51c-4943-955e-73627ed2193b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>4520c144-b4e4-453e-8161-587765e79c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_MainContent_lnkCalculate' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$MainContent$lnkCalculate&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))' and (text() = 'Calculate' or . = 'Calculate')]</value>
      <webElementGuid>a129621c-eed0-4b25-92ee-72ec90bd1e2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
