<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ctl00MainContenttxtLoanAmount</name>
   <tag></tag>
   <elementGuidId>2f6580d7-624b-471f-8c32-37cdad839872</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_MainContent_txtLoanAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_txtLoanAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfe1a3b1-fd2e-4295-bdfc-0c9aed8db8ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$txtLoanAmount</value>
      <webElementGuid>66d5547b-7d5e-4d72-92cb-5ce8e5556c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4732d544-51ed-4c07-a5c9-8283d0512045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>c1c8b6b1-1a82-45f7-8cbd-171f69338709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_txtLoanAmount</value>
      <webElementGuid>0f1029c8-8939-4190-afd1-7d79885cc829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputtextbox</value>
      <webElementGuid>e167dee1-b82e-4d6d-a796-1ebc769ce3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_txtLoanAmount&quot;)</value>
      <webElementGuid>5aed879a-4a37-4591-b7f1-05a7465ae4cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_MainContent_txtLoanAmount']</value>
      <webElementGuid>2747d1ac-ae98-4863-9577-f036c82e2de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[3]/article/div[4]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>7e9a7011-653e-40a5-a8fd-8eab3741a181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>f52a0e50-566b-4cce-bd3e-08b3e586b6bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$MainContent$txtLoanAmount' and @type = 'text' and @id = 'ctl00_MainContent_txtLoanAmount']</value>
      <webElementGuid>53225261-b389-4288-b6ed-31b020442209</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
