<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_30</name>
   <tag></tag>
   <elementGuidId>84277204-be53-48fe-bca9-c148d37262b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_MainContent_lblMonthlyPayment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MainContent_lblMonthlyPayment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>32679225-b4d1-419b-93da-e61ae1a96eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_lblMonthlyPayment</value>
      <webElementGuid>61ad2c23-4ea4-47d6-9b7d-67e8209d5c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formValue</value>
      <webElementGuid>78f59e8d-a22b-4c91-b836-451cea4b797a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$ 30</value>
      <webElementGuid>9fa158f2-254d-4963-9f4b-d715cf79e99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MainContent_lblMonthlyPayment&quot;)</value>
      <webElementGuid>86b98bba-2e7b-45e1-a8f3-32d3bcab443d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_MainContent_lblMonthlyPayment']</value>
      <webElementGuid>72cf58f0-1b56-4b05-9e57-f67b2efd9a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[3]/article/div[4]/table/tbody/tr[2]/td[2]/span</value>
      <webElementGuid>f38e9926-b2c4-43c2-8e54-93fab21ebaf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimum Monthly Payment:'])[1]/following::span[1]</value>
      <webElementGuid>ae444d97-0db8-4411-b347-a55dcf38aa61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan amount must be numeric.'])[1]/following::span[1]</value>
      <webElementGuid>821c4311-d8e8-4877-8b6c-ecb83ca9b785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculate'])[1]/preceding::span[1]</value>
      <webElementGuid>386e4bc5-9c02-4982-aee8-d636c66cef9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'ctl00_MainContent_lblMonthlyPayment', '&quot;', ')')])[1]/preceding::span[1]</value>
      <webElementGuid>3ac87596-8cd9-4078-bb6c-7a171f23bdbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$ 30']/parent::*</value>
      <webElementGuid>e4c81542-bbac-4b74-8d73-5725874516ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/span</value>
      <webElementGuid>bef19524-2de3-4230-b8f7-6e5ea04e9b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_MainContent_lblMonthlyPayment' and (text() = '$ 30' or . = '$ 30')]</value>
      <webElementGuid>8ce7b993-1893-4aed-9c3e-2e45d3d1bf19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
